using System.Collections.Immutable;
using Analyzer.Utilities;
using Dotnetarium.Analyzers.Cryptography;
using Dotnetarium.Analyzers.Taint;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Dotnetarium.Analyzers.Tests;

public sealed class MigrationExclusionTests
{
    [Fact]
    public async Task Real_ef_migrations_skip_all_taint_but_keep_constant_and_crypto_rules()
    {
        Assert.Equal(10, typeof(Migration).Assembly.GetName().Version!.Major);
        var compilation = Compile("""
            using System;
            using System.Diagnostics;
            using System.Net;
            using System.Security.Cryptography;
            using Microsoft.EntityFrameworkCore.Migrations;
            public abstract class BaseMigration : Migration {
                protected override void Down(MigrationBuilder builder) {}
            }
            public partial class SeedMigration : BaseMigration {
                protected override void Up(MigrationBuilder builder) {
                    Process.Start(Console.ReadLine());
                    _ = new NetworkCredential("seed", "secret-production-password");
                    using var aes = Aes.Create(); aes.Mode = CipherMode.ECB;
                }
            }
            public partial class SeedMigration {
                public static void Invoke(string input) => Process.Start(input);
                public static string Read() => Console.ReadLine();
                public static void Callback() { Action action = () => Process.Start(Console.ReadLine()); action(); }
                public class Helper { public void Run() => Process.Start(Console.ReadLine()); }
            }
            public class Host {
                public void OnlyMigration() { SeedMigration.Invoke(Console.ReadLine()); SeedMigration.Callback(); }
                public void Run() { SeedMigration.Invoke(Console.ReadLine()); Process.Start(Console.ReadLine()); }
            }
            namespace App.Migrations {
                public class Migration { public void Run() => Process.Start(Console.ReadLine()); }
            }
            """, """
            // <auto-generated />
            using System;
            using System.Diagnostics;
            using System.Net;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Infrastructure;
            public class SchemaSnapshot : ModelSnapshot {
                protected override void BuildModel(ModelBuilder builder) {
                    Process.Start(Console.ReadLine());
                    _ = new NetworkCredential("snapshot", "secret-production-password");
                }
            }
            public class UnrelatedGenerated {
                public void Run() { _ = new NetworkCredential("generated", "secret-production-password"); }
            }
            """);
        var analyzers = typeof(TaintAnalyzer).Assembly.GetTypes()
            .Where(type => !type.IsAbstract && typeof(TaintAnalyzer).IsAssignableFrom(type))
            .Select(type => (DiagnosticAnalyzer)Activator.CreateInstance(type)!)
            .Append(new HardcodedPasswordAnalyzer()).Append(new CryptographyAnalyzer()).ToImmutableArray();
        var diagnostics = await compilation.WithAnalyzers(analyzers).GetAnalyzerDiagnosticsAsync();
        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Id is "AD0001" or "DNA9000");
        Assert.Equal(2, diagnostics.Count(diagnostic => diagnostic.Id == "DNA0002"));
        Assert.Equal(2, diagnostics.Count(diagnostic => diagnostic.Id == "DNA0009"));
        Assert.Contains(diagnostics, diagnostic => diagnostic.Id == "DNA0014");
        Assert.DoesNotContain(diagnostics.Where(diagnostic => diagnostic.Id == "DNA0002"),
            diagnostic => diagnostic.GetMessage().Contains("SeedMigration") || diagnostic.GetMessage().Contains("SchemaSnapshot"));
        Assert.True(MigrationAnalysisExclusion.IsExcluded(compilation.GetTypeByMetadataName("SeedMigration")!));
        Assert.True(MigrationAnalysisExclusion.IsExcluded(compilation.GetTypeByMetadataName("SeedMigration+Helper")!));
        Assert.True(MigrationAnalysisExclusion.IsExcluded(compilation.GetTypeByMetadataName("SchemaSnapshot")!));
        Assert.False(MigrationAnalysisExclusion.IsExcluded(compilation.GetTypeByMetadataName("App.Migrations.Migration")!));
    }

    private static CSharpCompilation Compile(string code, string generated)
    {
        var references = ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!).Split(Path.PathSeparator)
            .Select(path => MetadataReference.CreateFromFile(path));
        var compilation = CSharpCompilation.Create("MigrationPolicy",
            [CSharpSyntaxTree.ParseText(code, path: "Seed.cs"), CSharpSyntaxTree.ParseText(generated, path: "Schema.Designer.cs")],
            references, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        Assert.DoesNotContain(compilation.GetDiagnostics(), diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
        return compilation;
    }
}
